output: generated

definitions:
  ts:
    types:
      int32: number
      int64: number
      double: number
      boolean: boolean
      string: string
      date: Date
    helpers:
      '"now()"': new Date()

generators:
  - name: TS Models
    template: templates/model.ts.go.tpl
    output: models/[model-].ts
    from: ts

  - name: TS Service
    template: templates/service.ts.go.tpl
    output: services/[model-].service.ts
    from: ts
