Auxiliary:
  id:
    type: int64
    pk: true
  name: string
  active: boolean
  idUser: int64
  userName: string
  # OPTIONS
  (list-filter): AuxiliaryListFilter
  (filter): AuxiliaryFilter

AuxiliaryListFilter:
  id:
    type: int64
    default: -1
  active:
    type: int32
    default: -1
  idUser:
    type: int64
    default: -1
  # OPTIONS
  (service_ignore): true

AuxiliaryFilter:
  id: { type: int64, pk: true }
  # OPTIONS
  (service_ignore): true

Vector:
  x: int64
  "y": int64

Foo:
  bar: Auxiliary
  vectors:
    type: Vector
